 CREATE TABLE COMTNUSERMNG
 (
 	USR_ID               		VARCHAR(20) NOT NULL,
 	PASSWORD              VARCHAR(200) NOT NULL,
 	PASSWORD_HINT      VARCHAR(100) ,
 	PASSWORD_CNSR     VARCHAR(100) ,
 	USR_NM               	VARCHAR(50) ,
 	ZIP                   		VARCHAR(6) ,
 	ADRES                 	VARCHAR(100) ,
 	AREA_NO               	VARCHAR(4) ,
 	USR_STTUS           	VARCHAR(15) ,
 	DETAIL_ADRES         VARCHAR(100) ,
 	END_TELNO             	VARCHAR(4)  ,
 	MBTLNUM               	VARCHAR(20)  ,
 	USR_FXNUM           	VARCHAR(20) ,
 	USR_EMAIL_ADRES  	VARCHAR(50) ,
 	MIDDLE_TELNO         VARCHAR(4) ,
 	SBSCRB_DE             	VARCHAR(14) ,
 	SEXDSTN_CODE      	VARCHAR(1) ,
 	ESNTL_ID              	VARCHAR(20) ,
 	LOCK_AT               	VARCHAR(1) ,
 	LOCK_CNT              	NUMERIC(3) ,
 	LOCK_LAST_PNTTM   VARCHAR(14) ,
 	CHANGE_DT					VARCHAR(14) ,
 	PRIMARY KEY (USR_ID)
 );

INSERT INTO COMTNUSERMNG ( USR_ID , PASSWORD , PASSWORD_HINT , PASSWORD_CNSR , USR_NM , ZIP , ADRES , AREA_NO , USR_STTUS , DETAIL_ADRES , END_TELNO , MBTLNUM , USR_FXNUM , USR_EMAIL_ADRES , MIDDLE_TELNO , SBSCRB_DE , SEXDSTN_CODE , ESNTL_ID , LOCK_AT , LOCK_CNT , CHANGE_DT )
 VALUES ( 'TESTUSER' , '473287f8298dba7163a897908958f7c0eae733e25d2e027992ea2edc9bed2fa8' , 'P02' , 'P0002' , '홍길동' , '23121' , 'adres' , '112' , 'A' , '111-335' , '6432' , '010-0000-3333' , '02-332-3332' , 'test@egov.go.kr' , '2332' , null , 'M' , null , 'N' , 0 , '20200623094810' );
INSERT INTO COMTNUSERMNG (USR_ID,PASSWORD,PASSWORD_HINT,PASSWORD_CNSR,USR_NM,ZIP,ADRES,AREA_NO,USR_STTUS,DETAIL_ADRES,END_TELNO,MBTLNUM,USR_FXNUM,USR_EMAIL_ADRES,MIDDLE_TELNO,SBSCRB_DE,SEXDSTN_CODE,ESNTL_ID, CHANGE_DT) 
 VALUES ('USER','473287f8298dba7163a897908958f7c0eae733e25d2e027992ea2edc9bed2fa8','P01','전자정부표준프레임워크센터','일반회원','100775','서울 중구 무교동 한국정보화진흥원','02','P','전자정부표준프레임워크센터','2059','1566-2059','1566-2059','egovframesupport@gmail.com','1566','20200623094810','F','USRCNFRM_00000000001', '20200623094810');

 
  CREATE TABLE COMTNAUTHORINFO
  (
  	AUTHOR_CODE VARCHAR(30) NOT NULL,
  	AUTHOR_NM VARCHAR(60),
  	AUTHOR_DC VARCHAR(200),
  	AUTHOR_CREAT_DT VARCHAR(14) NOT NULL,
  	CHANGE_DT VARCHAR(14) NOT NULL,
  	PRIMARY KEY (AUTHOR_CODE)
  );

INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DT, CHANGE_DT) VALUES('AUTH001', '기본권한', '시스템 기본 권한', '20200623094810', '20200623094810');
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DT, CHANGE_DT) VALUES('AUTH002', '권한관리', '권한관리 화면 편집 권한', '20200623094810', '20200623094810');
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DT, CHANGE_DT) VALUES('AUTH003', '권한그룹관리', '권한그룹관리 화면 편집 권한', '20200623094810', '20200623094810');


 CREATE TABLE COMTNAUTHORUSR
 (
 	AUTHOR_CODE VARCHAR(30) NOT NULL,
 	USR_ID VARCHAR(20) NOT NULL,
 	AUTHOR_GRP_CODE VARCHAR(30),
 	ADD_DT VARCHAR(14) NOT NULL,
 	PRIMARY KEY (AUTHOR_CODE,USR_ID)
 );

INSERT INTO COMTNAUTHORUSR (AUTHOR_CODE, USR_ID, AUTHOR_GRP_CODE, ADD_DT) VALUES ('AUTH001', 'TESTUSER', 'AUTHGRP001', '20200623094810');


 CREATE TABLE COMTNAUTHORGROUPINFO
 (
 	AUTHOR_GRP_CODE         VARCHAR(30) NOT NULL,
 	AUTHOR_GRP_NM           VARCHAR(60),
 	AUTHOR_GRP_DC           VARCHAR(200),
 	AUTHOR_GRP_CREAT_DT     VARCHAR(14),
 	CHANGE_DT               VARCHAR(14) NOT NULL,
 	PRIMARY KEY (AUTHOR_GRP_CODE)
 );

INSERT INTO COMTNAUTHORGROUPINFO (AUTHOR_GRP_CODE, AUTHOR_GRP_NM, AUTHOR_GRP_DC, AUTHOR_GRP_CREAT_DT, CHANGE_DT) VALUES('AUTHGRP001', '관리자', '시스템 운영 관리자', '20200623094810', '20200623094810'); 
INSERT INTO COMTNAUTHORGROUPINFO (AUTHOR_GRP_CODE, AUTHOR_GRP_NM, AUTHOR_GRP_DC, AUTHOR_GRP_CREAT_DT, CHANGE_DT) VALUES('AUTHGRP002', '사용자', '일반 사용자', '20200623094810', '20200623094810');


 CREATE TABLE COMTNAUTHORGROUPAUTH
 (
 	AUTHOR_GRP_CODE  VARCHAR(30) NOT NULL,
 	AUTHOR_CODE      VARCHAR(30) NOT NULL,
 	ADD_DT           VARCHAR(14) NOT NULL,
 	PRIMARY KEY (AUTHOR_GRP_CODE, AUTHOR_CODE)
 );

INSERT INTO COMTNAUTHORGROUPAUTH (AUTHOR_GRP_CODE, AUTHOR_CODE, ADD_DT) VALUES('AUTHGRP001', 'AUTH001', '20200623094810'); 



 CREATE TABLE COMTNMENUINFO 
 (
   `MENU_NO` DECIMAL(20,0) NOT NULL COMMENT '메뉴번호',
   `MENU_NM` VARCHAR(60) NOT NULL COMMENT '메뉴명',
   `PROGRM_FILE_NM` VARCHAR(60) NOT NULL COMMENT '프로그램파일명',
   `UPPER_MENU_NO` DECIMAL(20,0) COMMENT '상위메뉴번호',
   `MENU_ORDR` DECIMAL(5,0) NOT NULL COMMENT '메뉴순서',
   `MENU_DC` VARCHAR(250) COMMENT '메뉴설명',
   `RELATE_IMAGE_PATH` VARCHAR(100) COMMENT '관계이미지경로',
   `RELATE_IMAGE_NM` VARCHAR(60) COMMENT '관계이미지명',
   PRIMARY KEY (`MENU_NO`)
 );

INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('root', 'dir', 0, 0, 1, 'root', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('로그인', 'Login', 1000000, 0, 1, '로그인', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('권한 관리', 'dir', 2000000, 0, 2, '권한 관리', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('권한 등록', 'AuthInfo?callType=c&authId=', 2010000, 2000000, 1, '권한 등록', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('권한 목록 조회', 'AuthList', 2020000, 2000000, 2, '권한 목록 조회', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('권한 사용자 등록', 'AuthInfoSetUsr?callType=c&authId=', 2030000, 2000000, 3, '권한 사용자 등록', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('권한그룹 관리', 'dir', 3000000, 0, 3, '권한그룹 관리', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('권한그룹 등록', 'AuthGroupInfo?callType=c&authGrpId=', 3010000, 3000000, 1, '권한그룹 등록', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('권한그룹 목록 조회', 'AuthGrpList', 3020000, 3000000, 2, '권한그룹 목록 조회', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('권한그룹 권한 등록', 'AuthGrpDetailSetAth?callType=c&authGrpId=', 3030000, 3000000, 3, '권한그룹 권한 등록', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('권한그룹 사용자 등록', 'AuthGrpDetailSetUsr?callType=c&authGrpId=', 3040000, 3000000, 4, '권한그룹 사용자 등록', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('권한 메뉴 관리', 'dir', 4000000, 0, 4, '권한 메뉴 관리', '/', '/');
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM) VALUES ('권한그룹 메뉴 등록', 'AuthGroupSetMenu', 4010000, 4000000, 1, '권한그룹 메뉴 등록', '/', '/');


 CREATE TABLE COMTNMENUCREATDTLS 
 (
   MENU_NO 				DECIMAL(20,0) 	NOT NULL COMMENT '메뉴번호',
   AUTHOR_GRP_CODE 		VARCHAR(30) 	NOT NULL COMMENT '권한그룹코드',
   MAPNG_CREAT_ID 	VARCHAR(30) 	COMMENT '매핑생성ID',
   PRIMARY KEY (`MENU_NO`,`AUTHOR_GRP_CODE`)
 );

INSERT INTO COMTNMENUCREATDTLS (MENU_NO, AUTHOR_GRP_CODE) VALUES (1000000, 'AUTHGRP001');
INSERT INTO COMTNMENUCREATDTLS (MENU_NO, AUTHOR_GRP_CODE) VALUES (2000000, 'AUTHGRP001');
INSERT INTO COMTNMENUCREATDTLS (MENU_NO, AUTHOR_GRP_CODE) VALUES (2020000, 'AUTHGRP001');
INSERT INTO COMTNMENUCREATDTLS (MENU_NO, AUTHOR_GRP_CODE) VALUES (4000000, 'AUTHGRP001');
INSERT INTO COMTNMENUCREATDTLS (MENU_NO, AUTHOR_GRP_CODE) VALUES (4010000, 'AUTHGRP001');
 